apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: order-consumer
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/"
        prometheus.io/port: "8000"
      labels:
        app: order-consumer
    spec:
      containers:
      - name: consumer
        image: <acr_name>.azurecr.io/order-consumer:v1
        env:
          - name: CONNECTION_STR
            valueFrom:
              secretKeyRef:
                name: service-bus-connection
                key: primary-connection-string
                optional: false
          - name: QUEUE_NAME
            value: orders
        resources:
          requests:
            cpu: 200m